// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BPAUnaryCA.proto

public interface SupportRequest1OrBuilder extends
    // @@protoc_insertion_point(interface_extends:SupportRequest1)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * server streaming - one request
   * </pre>
   *
   * <code>string available_day = 1;</code>
   */
  java.lang.String getAvailableDay();
  /**
   * <pre>
   * server streaming - one request
   * </pre>
   *
   * <code>string available_day = 1;</code>
   */
  com.google.protobuf.ByteString
      getAvailableDayBytes();
}
