// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BPAUnaryCA.proto

public interface SupportResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SupportResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string cardPay = 1;</code>
   */
  java.lang.String getCardPay();
  /**
   * <code>string cardPay = 1;</code>
   */
  com.google.protobuf.ByteString
      getCardPayBytes();
}
