// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BPAUnaryCA.proto

public interface SupportRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SupportRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string payment = 1;</code>
   */
  java.lang.String getPayment();
  /**
   * <code>string payment = 1;</code>
   */
  com.google.protobuf.ByteString
      getPaymentBytes();
}
