// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BPAUnaryCA.proto

public interface SupportResponse1OrBuilder extends
    // @@protoc_insertion_point(interface_extends:SupportResponse1)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * server streaming - many responses at one time
   * </pre>
   *
   * <code>string course_start_June_14 = 1;</code>
   */
  java.lang.String getCourseStartJune14();
  /**
   * <pre>
   * server streaming - many responses at one time
   * </pre>
   *
   * <code>string course_start_June_14 = 1;</code>
   */
  com.google.protobuf.ByteString
      getCourseStartJune14Bytes();

  /**
   * <code>string course_start_June_28 = 2;</code>
   */
  java.lang.String getCourseStartJune28();
  /**
   * <code>string course_start_June_28 = 2;</code>
   */
  com.google.protobuf.ByteString
      getCourseStartJune28Bytes();

  /**
   * <code>string course_start_August_16 = 3;</code>
   */
  java.lang.String getCourseStartAugust16();
  /**
   * <code>string course_start_August_16 = 3;</code>
   */
  com.google.protobuf.ByteString
      getCourseStartAugust16Bytes();
}
